move bacteria and fungi single node runs into the batch system too

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -241,7 +241,19 @@ Bacteria:validation:
     - echo "Logging to ${CI_SCRATCH}/validation-$dt.log and .err at $(date) on $(uname -n) in $(pwd)"
     - env
     - set -x
-    - ./ci/ubuntu.validation.sh ${BASE}
+    - cd ${CI_SCRATCH}
+    - test_file=validation_test-$dt
+    - rm -f ${test_file}*
+    - |
+      batch << END_TEXT
+        export PATH=${PATH} # keep CI path within batch
+        ./ci/ubuntu.validation.sh ${BASE} >${test_file}.log 2>&1 && \
+        echo Success > ${test_file} || echo Failed > ${test_file}
+      END_TEXT
+    - while [ ! -f ${test_file} ] ; do echo "Waiting for job to complete via batch subsystem on ${test_file}"; date; uptime ; sleep 60  ; done
+    - cat ${test_file}*
+    - grep Success ${test_file} || FAILED="${FAILED} Could not run ${test_file}"
+    - if [ -z "$FAILED" ] ; then echo "OK" ; else echo "Something failed somehow - ${FAILED}" ; false ; fi
     - echo "Completed successfully on bacteria"
 
 Bacteria:accuracy:
@@ -266,18 +278,31 @@ Bacteria:accuracy:
     - echo "Logging to ${CI_SCRATCH}/accuracy-$dt.log and .err at $(date) on $(uname -n) in $(pwd) $(uptime)"
     - env
     - set -x
-    - ./ci/ubuntu.accuracy.sh ${BASE}
-    - echo "Extra full CI run on bacteria and fungi using GPUs scheduled via the batch system"
     - cd ${CI_SCRATCH}
-    - rm -f full_test_status
+    - test_file=ci_asm_qual_full_test-$dt
+    - rm -f ${test_file}*
     - |
       batch << END_TEXT
         export PATH=${PATH} # keep CI path within batch
-        ./mhm2-rel/bin/ci_asm_qual_test-full.sh --procs=32 --nodes=2 >full_test.log 2>&1  && echo Success > full_test_status || echo Failed > full_test_status
+        ./ci/ubuntu.accuracy.sh ${BASE} >>${test_file}.log 2>&1 && \
+        echo Success > ${test_file} || echo Failed > ${test_file}
       END_TEXT
-    - while [ ! -f full_test_status ] ; do echo "Waiting for job to complete via batch subsystem"; date; uptime ; sleep 60  ; done
-    - cat full_test.log
-    - grep Success full_test_status || FAILED="${FAILED} Could not run ci_asm_qual_test-full"
+    - while [ ! -f ${test_file} ] ; do echo "Waiting for job to complete via batch subsystem: ${test_file}"; date; uptime ; sleep 60  ; done
+    - cat ${test_file}*
+    - grep Success ${test_file} || FAILED="${FAILED} Could not run ${test_file}"
+    - if [ -z "$FAILED" ] ; then echo "OK" ; else echo "Something failed somehow - ${FAILED}" ; false ; fi
+    - echo "Extra full CI run on bacteria and fungi using GPUs scheduled via the batch system"
+    - test_file=ci_asm_qual_full_test_2node-$dt
+    - rm -f ${test_file}*
+    - |
+      batch << END_TEXT
+        export PATH=${PATH} # keep CI path within batch
+        ./mhm2-rel/bin/ci_asm_qual_test-full.sh --procs=32 --nodes=2 >>${test_file}.log 2>&1 && \
+        echo Success > ${test_file} || echo Failed > ${test_file}
+      END_TEXT
+    - while [ ! -f ${test_file} ] ; do echo "Waiting for job to complete via batch subsystem: ${test_file}"; date; uptime ; sleep 60  ; done
+    - cat ${test_file}*
+    - grep Success ${test_file} || FAILED="${FAILED} Could not run ${test_file}"
     - if [ -z "$FAILED" ] ; then echo "OK" ; else echo "Something failed somehow - ${FAILED}" ; false ; fi
     - if [ ! -f ./test-arctic-samples/final_assembly.fasta ] ; then FAILED="${FAILED} Did not find final_assembly.fasta on rel" ; fi
     - if [ -z "$FAILED" ] ; then echo "OK" ; else echo "Something failed somehow - ${FAILED}" ; false ; fi
@@ -336,7 +361,20 @@ Fungi:validation:
     - echo "Logging to ${CI_SCRATCH}/validation-$dt.log and .err at $(date) on $(uname -n) in $(pwd)"
     - env
     - set -x
-    - ./ci/ubuntu.validation.sh ${BASE}
+    - cd ${CI_SCRATCH}
+    - test_file=validation_test-$dt
+    - rm -f ${test_file}*
+    - |
+      batch << END_TEXT
+        export PATH=${PATH} # keep CI path within batch
+        ./ci/ubuntu.validation.sh ${BASE} >> ${test_file}.log 2>&1 && \
+        echo Success > ${test_file} || echo Failed > ${test_file}
+      END_TEXT
+    - while [ ! -f ${test_file} ] ; do echo "Waiting for job to complete via batch subsystem on ${test_file}"; date; uptime ; sleep 60  ; done
+    - cat ${test_file}*
+    - grep Success ${test_file} || FAILED="${FAILED} Could not run ${test_file}"
+    - if [ -z "$FAILED" ] ; then echo "OK" ; else echo "Something failed somehow - ${FAILED}" ; false ; fi
+    - echo "Completed successfully on fungi"
 
 Fungi:accuracy:
   stage: accuracy
@@ -360,18 +398,31 @@ Fungi:accuracy:
     - echo "Logging to ${CI_SCRATCH}/accuracy-$dt.log and .err at $(date) on $(uname -n) in $(pwd) $(uptime)"
     - env
     - set -x
-    - ./ci/ubuntu.accuracy.sh ${BASE}
-    - echo "Extra full CI run on fungi and bacteria CPU only scheduled via the batch system"
     - cd ${CI_SCRATCH}
-    - rm -f full_test_status
+    - echo "Single node CI run on CPU only scheduled via the batch system"
+    - test_file=ci_asm_qual_full_test-$dt
+    - rm -f ${test_file}*
     - |
       batch << END_TEXT
         export PATH=${PATH} # keep CI path within batch
-        ./mhm2-rel/bin/ci_asm_qual_test-full.sh --procs=32 --nodes=2 >full_test.log 2>&1  && echo Success > full_test_status || echo Failed > full_test_status
+       ./ci/ubuntu.accuracy.sh ${BASE} >> ${test_file}.log 2>&1 && \
+       echo Success > ${test_file} || echo Failed > ${test_file}
+    - while [ ! -f ${test_file} ] ; do echo "Waiting for job to complete via batch subsystem: ${test_file}"; date; uptime ; sleep 60  ; done
+    - cat ${test_file}*
+    - grep Success ${test_file} || FAILED="${FAILED} Could not run ${test_file}"
+    - if [ -z "$FAILED" ] ; then echo "OK" ; else echo "Something failed somehow - ${FAILED}" ; false ; fi
+    - echo "Extra full CI run on both fungi and bacteria CPU only scheduled via the batch system"
+    - test_file=ci_asm_qual_full_test_2node-$dt
+    - rm -f ${test_file}*
+    - |
+      batch << END_TEXT
+        export PATH=${PATH} # keep CI path within batch
+       ./mhm2-rel/bin/ci_asm_qual_test-full.sh --procs=32 --nodes=2 >>${test_file}.log 2>&1  && \
+       echo Success > ${test_file} || echo Failed > ${test_file}
       END_TEXT
-    - while [ ! -f full_test_status ] ; do echo "Waiting for job to complete via batch subsystem"; date; uptime ; sleep 60  ; done
-    - cat full_test.log
-    - grep Success full_test_status || FAILED="${FAILED} Could not run ci_asm_qual_test-full"
+    - while [ ! -f ${test_file} ] ; do echo "Waiting for job to complete via batch subsystem: ${test_file}"; date; uptime ; sleep 60  ; done
+    - cat ${test_file}*
+    - grep Success ${test_file} || FAILED="${FAILED} Could not run ${test_file}"
     - if [ -z "$FAILED" ] ; then echo "OK" ; else echo "Something failed somehow - ${FAILED}" ; false ; fi
     - if [ ! -f ./test-arctic-samples/final_assembly.fasta ] ; then FAILED="${FAILED} Did not find final_assembly.fasta on rel" ; fi
     - if [ -z "$FAILED" ] ; then echo "OK" ; else echo "Something failed somehow - ${FAILED}" ; false ; fi
